### PR TITLE
Copy Gemfile.lock into the docker container if there is one

### LINKED ISSUE #40: Docker build doesn't respect `Gemfile.lock`
**Describe the bug**

My project has a `Gemfile` and a `Gemfile.lock` but when I `sls deploy` I end up with a different set of gems being installed than what is specified in the lock file. If I remove `Gemfile.lock` the build process also does not generate one, which it seems like it should.

**Error Stack Trace**

None

**Example Config files**

My `Gemfile.lock` contains:
```
aws-sdk-core (3.113.0)
```

But the `.serverless/ruby_layer/gemLayer.zip` package contains version `3.113.1`.
```
unzip -l .serverless/ruby_layer/gemLayer.zip | grep aws-sdk-core
   0  04-02-2021 18:17   ruby/2.7.0/gems/aws-sdk-core-3.113.1/
...
```

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS]
 - NodeVersion [e.g. 12.16.1]
 - Ruby version [e.g. 2.5.8]
 - Bundler version [e.g. 2.1.2]

**Additional context**

### PR DESCRIPTION
**Pull request by jagthedrummer**
Should fix #40

### CODE REVIEW

**Comment by navarasu** [comment]
Did you test this change in your local? Is it solving your problem?

**Comment by jagthedrummer** [comment]
@navarasu I have tested it and just found that I needed to add a second commit to get everything working. It's doing what I expect locally and does solve the problem of mismatched gem versions.

**Comment by navarasu** [comment]
Thanks, Jeremy. Please add your example for gemfile lock case under the `example` folder. I will update the test case from my side

**Comment by jagthedrummer** [comment]
Hey @navarasu, I wasn't entirely sure what you'd want for an example, but I did take a first stab at it. Let me know if there's anything else you need.

Of note, the `Gemfile.lock` specifies `aws-partitions (1.440.0)` but the most recent version is `1.441.0` which is what you should get if `Gemfile.lock` isn't being respected.

**Comment by Mongey** [comment]
@navarasu anything stopping this from being merged?

**Comment by navarasu** [comment]
The ruby file has to be update `examples/use-docker-with-gemfile-lock/handler.rb` need to add test case for it.

**Comment by navarasu** [comment]
Today I have created a proper gemfile.lock example and test case for both basic and docker case.
* Basic case without docker works without issue.
* With docker case, we need to take care of missing bundler version else it will fail with following error
```
 Could not find 'bundler' (1.16.6) required by your /var/gem_build/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.6`
```

**Comment by navarasu** [comment]
Created new PR https://github.com/navarasu/serverless-ruby-layer/pull/45 for testcase and fix

**Pull request merged**
